import { GetObjectCommand, NoSuchKey, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { Env } from '../../config/env';

export const IMAGE_TYPES = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
} as const;

export type ImageType = keyof typeof IMAGE_TYPES;

const CONTENT_TYPES: Record<string, ImageType> = { jpg: 'image/jpeg', png: 'image/png', webp: 'image/webp' };

/** Keys are generated by the server, so anything else is rejected before it touches the disk. */
const KEY_PATTERN = /^[a-z]+\/\d{4}-\d{2}\/[0-9a-f-]{36}\.(jpg|png|webp)$/;

/**
 * Keeps uploaded files in an S3-compatible bucket when one is configured, otherwise on local disk
 * under STORAGE_DIR. Files are always served through the API, so the bucket can stay private.
 */
@Injectable()
export class StorageService {
  private readonly logger = new Logger(StorageService.name);
  private readonly root: string;
  private readonly publicUrl: string;
  private readonly bucket: { client: S3Client; name: string } | null;

  constructor(config: ConfigService<Env, true>) {
    this.root = resolve(config.get('STORAGE_DIR', { infer: true }));
    this.publicUrl = config.get('PUBLIC_API_URL', { infer: true });

    const name = config.get('S3_BUCKET', { infer: true });
    this.bucket = name
      ? {
          name,
          client: new S3Client({
            endpoint: config.get('S3_ENDPOINT', { infer: true }),
            region: config.get('S3_REGION', { infer: true }),
            credentials: {
              accessKeyId: config.get('S3_ACCESS_KEY_ID', { infer: true })!,
              secretAccessKey: config.get('S3_SECRET_ACCESS_KEY', { infer: true })!,
            },
            forcePathStyle: true,
          }),
        }
      : null;
  }

  static isKey(key: string): boolean {
    return KEY_PATTERN.test(key);
  }

  async put(folder: string, body: Buffer, type: ImageType): Promise<string> {
    const month = new Date().toISOString().slice(0, 7);
    const key = `${folder}/${month}/${crypto.randomUUID()}.${IMAGE_TYPES[type]}`;
    if (this.bucket) {
      await this.bucket.client.send(
        new PutObjectCommand({ Bucket: this.bucket.name, Key: key, Body: body, ContentType: type }),
      );
      return key;
    }
    const path = resolve(this.root, key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    return key;
  }

  async get(key: string): Promise<{ body: Buffer; contentType: ImageType } | null> {
    if (!StorageService.isKey(key)) return null;
    const contentType = CONTENT_TYPES[key.split('.').pop()!]!;
    if (this.bucket) {
      try {
        const object = await this.bucket.client.send(
          new GetObjectCommand({ Bucket: this.bucket.name, Key: key }),
        );
        const bytes = await object.Body?.transformToByteArray();
        return bytes ? { body: Buffer.from(bytes), contentType } : null;
      } catch (error) {
        if (!(error instanceof NoSuchKey))
          this.logger.warn(`Could not read ${key}: ${(error as Error).name}`);
        return null;
      }
    }
    try {
      const body = await readFile(resolve(this.root, key));
      return { body, contentType };
    } catch {
      return null;
    }
  }

  url(key: string): string;
  url(key: string | null | undefined): string | null;
  url(key: string | null | undefined): string | null {
    return key ? `${this.publicUrl}/v1/files/${key}` : null;
  }
}

/** Identifies an image from its first bytes; the declared content type is not trusted. */
export function sniffImage(bytes: Buffer): ImageType | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return 'image/jpeg';
  if (bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])))
    return 'image/png';
  if (bytes.subarray(0, 4).toString('ascii') === 'RIFF' && bytes.subarray(8, 12).toString('ascii') === 'WEBP')
    return 'image/webp';
  return null;
}

/** Decodes a `data:image/...;base64,` URL produced by a canvas, checking the bytes really are an image. */
export function decodeImageDataUrl(dataUrl: string): { body: Buffer; type: ImageType } | null {
  const match = /^data:image\/(?:jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl);
  if (!match) return null;
  const body = Buffer.from(match[1]!, 'base64');
  const type = sniffImage(body);
  return type ? { body, type } : null;
}
