import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { Env } from '../../config/env';

export const IMAGE_TYPES = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
} as const;

export type ImageType = keyof typeof IMAGE_TYPES;

const CONTENT_TYPES: Record<string, ImageType> = { jpg: 'image/jpeg', png: 'image/png', webp: 'image/webp' };

/** Keys are generated by the server, so anything else is rejected before it touches the disk. */
const KEY_PATTERN = /^[a-z]+\/\d{4}-\d{2}\/[0-9a-f-]{36}\.(jpg|png|webp)$/;

/**
 * Stores uploaded files on local disk under STORAGE_DIR. The interface is deliberately the
 * shape of an object store, so moving to S3 means replacing this class and nothing else.
 */
@Injectable()
export class StorageService {
  private readonly root: string;
  private readonly publicUrl: string;

  constructor(config: ConfigService<Env, true>) {
    this.root = resolve(config.get('STORAGE_DIR', { infer: true }));
    this.publicUrl = config.get('PUBLIC_API_URL', { infer: true });
  }

  static isKey(key: string): boolean {
    return KEY_PATTERN.test(key);
  }

  async put(folder: string, body: Buffer, type: ImageType): Promise<string> {
    const month = new Date().toISOString().slice(0, 7);
    const key = `${folder}/${month}/${crypto.randomUUID()}.${IMAGE_TYPES[type]}`;
    const path = resolve(this.root, key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    return key;
  }

  async get(key: string): Promise<{ body: Buffer; contentType: ImageType } | null> {
    if (!StorageService.isKey(key)) return null;
    try {
      const body = await readFile(resolve(this.root, key));
      return { body, contentType: CONTENT_TYPES[key.split('.').pop()!]! };
    } catch {
      return null;
    }
  }

  url(key: string): string;
  url(key: string | null | undefined): string | null;
  url(key: string | null | undefined): string | null {
    return key ? `${this.publicUrl}/v1/files/${key}` : null;
  }
}

/** Identifies an image from its first bytes; the declared content type is not trusted. */
export function sniffImage(bytes: Buffer): ImageType | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return 'image/jpeg';
  if (bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])))
    return 'image/png';
  if (bytes.subarray(0, 4).toString('ascii') === 'RIFF' && bytes.subarray(8, 12).toString('ascii') === 'WEBP')
    return 'image/webp';
  return null;
}

/** Decodes a `data:image/...;base64,` URL produced by a canvas, checking the bytes really are an image. */
export function decodeImageDataUrl(dataUrl: string): { body: Buffer; type: ImageType } | null {
  const match = /^data:image\/(?:jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl);
  if (!match) return null;
  const body = Buffer.from(match[1]!, 'base64');
  const type = sniffImage(body);
  return type ? { body, type } : null;
}
